REL-942846: Publish Relativity Server DataTransfer SDK
relativityone/server-datatransfer-relativity-data-transfer-legacy-sdk pull request #12
Opened 2024-05-09 10:42 UTC by ravikonnur

2024-05-13 19:41 UTC, briankesecker-relativity reviewed
Change log is out-of-order chronologically.  Expected?

2024-05-14 14:34 UTC, ravikonnur commented
> Change log is out-of-order chronologically. Expected?

We have taken change log based on the commit dates. Please suggest me if I am missing anything here.

2024-05-15 11:21 UTC, shivarajkamadod submitted a review, later dismissed

2024-05-15 11:43 UTC, sameerrelone submitted a review, later dismissed

2024-05-15 13:02 UTC, dhanushsathukumati commented on version.txt
> -24000.0.5
Could you please check the below link to make sure the version matches the required 5000.0.0 as per versioning strategy.

https://github.com/relativityone/server-adr/blob/main/00013-server-versioning-strategy.md

2024-05-15 13:03 UTC, dhanushsathukumati commented on version.txt
> +24000.0.6
Could you please check the below link to make sure the version matches the required 5000.0.0 as per versioning strategy.

https://github.com/relativityone/server-adr/blob/main/00013-server-versioning-strategy.md

2024-05-15 13:13 UTC, ravikonnur commented on version.txt
> +24000.0.6
For Highly coupled need to consider version 24000

2024-05-15 13:21 UTC, briankesecker-relativity commented on rap.yml
> +    RelativityBranch: 'release-12.3-2023-patch2'
I expect that these values do not appear in `main` branch.

2024-05-15 13:21 UTC, briankesecker-relativity commented on rap.yml
> +    DeployHotfixOrPatch: true
I expect that these values do not appear in `main` branch.

2024-05-16 07:40 UTC, ravikonnur commented on rap.yml
> +    DeployHotfixOrPatch: true
This change came from release 2023 branch, let me know this change is needed or not in main branch

2024-05-16 07:40 UTC, ravikonnur commented on rap.yml
> +    RelativityBranch: 'release-12.3-2023-patch2'
This change came from release 2023 branch, let me know this change is needed or not in main branch

2024-05-16 14:27 UTC, briankesecker-relativity commented on rap.yml
> +    RelativityBranch: 'release-12.3-2023-patch2'
Most server repositories keep this field as empty string.  Check this query https://github.com/search?q=org%3Arelativityone+RelativityBranch+path%3A*.yml&type=code&p=4

@scottmcburney Will this be a problem once merged to main branch?

2024-05-16 14:28 UTC, briankesecker-relativity commented on rap.yml
> +    DeployHotfixOrPatch: true
I don't find any Server repos that have this parameter defined.  https://github.com/search?q=org%3Arelativityone+DeployHotfixOrPatch+path%3A*.yml&type=code

@scottmcburney Will this be a problem once merged to main branch?

2024-05-17 12:54 UTC, ravikonnur commented on rap.yml
> +    DeployHotfixOrPatch: true
@scottmcburney Any inputs on the above changes.

2024-05-20 13:00 UTC, scottmcburney commented on rap.yml
> +    DeployHotfixOrPatch: true
"DeployHotfixOrPatch" was added by server-deploy.  You do NOT want it to be "True" in the main branch. 
server-deploy could supply more details.

2024-05-20 14:55 UTC, ravikonnur commented on rap.yml
> +    DeployHotfixOrPatch: true
@jaganganta, Can you please share inputs on this.
Cc: @shivarajkamadod

2024-05-20 16:04 UTC, chinmoyeep commented on rap.yml
> +    DeployHotfixOrPatch: true
@ravikonnur: "**DeployHotfixOrPatch**" parameter should be added only for Patch/Hotfix branch. It is documented in this Einstein page [https://einstein.kcura.com/x/c6nZJQ](https://einstein.kcura.com/x/c6nZJQ)

2024-05-22 08:25 UTC, ravikonnur commented on rap.yml
> +    RelativityBranch: 'release-12.3-2023-patch2'
Updated RelativityBranch value to empty

2024-05-22 08:27 UTC, ravikonnur commented on rap.yml
> +    DeployHotfixOrPatch: true
Removed "DeployHotfixOrPatch" parameter as its not required for main branch.

2024-05-22 15:05 UTC, shivarajkamadod approved these changes

2024-05-24 11:39 UTC, dhanushsathukumati approved these changes

2024-05-24 14:50 UTC, shivarajkamadod commented on version.txt
> +24000.0.7
This SDK internal dependency is highly coupled with relativity.

2024-05-24 14:51 UTC, shivarajkamadod approved these changes

2024-05-24 21:13 UTC, griffin-metevia requested changes
This pull request shouldn't be merged until the release version of Relativity.Server.DataTransfer.SDK has been published.

2024-05-26 16:49 UTC, shivarajkamadod commented
> This pull request shouldn't be merged until the release version of Relativity.Server.DataTransfer.SDK has been published.

@griffin-metevia I think that you wanted to add a comment on this PR - https://github.com/relativityone/server-datatransfer-transfer-api-legacy/pull/6.

2024-05-26 16:51 UTC, griffin-metevia approved these changes

2024-05-26 18:56 UTC, scott-parillo approved these changes

2024-05-26 23:25 UTC, merged